config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'
  
  resources :about, only: [:index]
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
  
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :create, :new]
    resources :sales, only: [:index, :new]
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category
  has_many :reviews

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController <  Admin::BaseAdminController
  
  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
    @review = @product.reviews.find_by(user_id: current_user) || Review.new
  end

end

app/views/products/_product.html.erb
<article class="product">
  <header>
    <%= link_to product do %>
      <%= image_tag product.image.thumb, alt: product.name %>
      <h4><%= product.name %></h4>
    <% end %>
  </header>
  <p class="description">
    <%= product.description %>
  </p>
  <footer class="actions">
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn btn-primary' , method: :post do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
    <% end %>
    <%= link_to product, class: 'btn btn-default pull-right' do %>
      Details &raquo;
    <% end %>
  </footer>

  <aside class="price">
    <%= humanized_money_with_symbol product.price %>
  </aside>
  <% if product.quantity == 0 %>
  <aside class="sold-out">
    SOLD OUT!
  </aside>  
  <% end %>
</article>

app/views/products/_review.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Reviewer: <%= review.user.first_name %> <%= review.user.last_name %></h3>
  </div>
  <div class="panel-body">
      <%= review.description %>
  </div>
  <div class="panel-footer">
      Rating: <%= review.rating %>
      <% if current_user && review.user_id == current_user.id %>
        <%= link_to (fa_icon 'trash-o', class: 'pull-right'), product_review_path(@product, review),
        data: {:confirm => 'Are you sure?'}, :method => :delete %>
      <% end %>
  </div>
</div>

app/views/products/index.html.erb
<section class="products-index">

  <header class="page-header">
    <h1>Products</h1>
  </header>
  <% if active_sale? %>
    <p class="alert alert-info text-center">
      There's an active <%= "Back To School"  %> sale going on! 
      Everything is <%= "15" %>% off!
  <% end %>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/products/show.html.erb
<section class="products-show">

  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @product.name %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.quantity %></dd>
          <dt>Price</dt>
          <dd><%= humanized_money_with_symbol @product.price %></dd>
        </dl>
      </div>
    </div>

    <div class="col-sm-8 col-sm-offset-4">
      <h2>Reviews</h2>
      <hr>
      <% if current_user && !@review.persisted? %>
        <%= form_for [@product, @review] do |f| %>
        <h4>Write a review!</h4>
          <div class="form-group">
            <label for="review_description">Description</label>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label for="review_rating">Rating</label>
            <%= f.select :rating, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].reverse, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.submit 'submit', class: 'btn btn-primary' %>
          </div>
        <% end %>
      <% elsif current_user %>
        <h4>You have already submitted a review. Thanks!</h4>
      <% else %>
        <h4>Please login to write a review</h4>
      <% end %>

      <% if !@product.reviews.empty? %>
        <% @product.reviews.reverse.each do |review| %>
          <%= render 'review', review: review %>
        <% end %>
      <% else %>
        <p>There are no reviews for this item yet!</p>
      <% end %>
    </div>

  </article>

</section>